[package]
name = "turtle-syntax"
version = "1.0.1"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
edition = "2018"
categories = ["parsing"]
keywords = ["turtle", "rdf", "parser"]
description = "RDF Turtle parser"
repository = "https://github.com/timothee-haudebourg/turtle-syntax"
documentation = "https://docs.rs/turtle-syntax"
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
source-span = "^2.1.1"
iref = "^1.1"

[dev-dependencies]
utf8-decode = "^1.0"
