[package]
name = "turtle"
version = "0.1.0"
authors = ["Timothée Haudebourg <timothee.haudebourg@hemisemi.fr>"]
edition = "2018"

[dependencies]
source-span = "*"
utf8-decode = "*"
grdf = { path = "../grdf" }
curie = "*"
ordered-float = "*"
