edition = "2018"
tab_spaces = 4
hard_tabs = true
error_on_unformatted = true
fn_single_line = true
format_code_in_doc_comments = false
format_macro_matchers = true
match_arm_blocks = true
reorder_impl_items = true
use_field_init_shorthand = true
normalize_comments = true
wrap_comments = true
